version: '3.8'

services:
  cheeseboard:
    container_name: cheeseboard
    image: cheeseboard
    build:
      context: .
      dockerfile: front/Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"