[tr-id.domestic-stock]
inquire-price = "FHKST01010100"
inquire-conclusion = "FHKST01010300"
inquire-periodic-price = "FHKST03010100"

[tr-id.domestic-future-option]
inquire-price = "FHMIF10000000"

[tr-id.overseas-stock]
inquire-price = "HHDFS00000300"
inquire-periodic-price = "HHDFS76240000"
inquire-periodic-forex = "FHKST03030100"

[uri.origin]
production = "https://openapi.koreainvestment.com:9443"

[uri.OAuth]
approval = "/oauth2/Approval" # 실시간 (웹소켓) 접속키 발급
hashkey = "/uapi/hashkey" # 해시키 발급
access_token_request = "/oauth2/tokenP" # 액세스 토큰 발급
access_token_revocation = "/oauth2/revokeP" # 액세스 토큰 폐기

[uri.domestic-stock]
inquire-price = "/uapi/domestic-stock/v1/quotations/inquire-price" # 주식현재가 시세
inquire-conclusion = "/uapi/domestic-stock/v1/quotations/inquire-ccnl" # 주식현재가 체결
inquire-periodic-price = "/uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice" # 국내주식기간별시세

[uri.domestic-future-option]
inquire-price = "/uapi/domestic-futureoption/v1/quotations/inquire-price" # 선물/옵션 현재가

[uri.overseas-stock]
inquire-price = "/uapi/overseas-price/v1/quotations/price" # 해외주식 현재체결가
inquire-periodic-price = "/uapi/overseas-price/v1/quotations/dailyprice" # 해외주식 기간별시세
inquire-periodic-forex = "/uapi/overseas-price/v1/quotations/inquire-daily-chartprice" # 해외주식 종목/지수/환율기간별시세(일/주/월/년)

[market-code]
Nasdaq = "NAS"
NYSE = "NYS"
AMEX = "AMS"
